# Workflow name
name: 'Chromatic Visual Tests'

# Event for the workflow
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # 👇 Compress and upload the entire storybook to chromatic, required for large projects
          zip: true
          # 👇 Auto accept changes on main branch
          autoAcceptChanges: 'main'
          # 👇 Exit with code 0 regardless of changes
          exitZeroOnChanges: true
